# This program takes the pairs of files generated by 
# the beautiful data wrangler and turns them into a 
# nice feature set for TensorFlow

import os

moleculeList = open("../formatted_data/moleculeidlist.txt", "r")
newMolList = open("../formatted_data/numberedmoleculeidlist.txt", "w")

for mol in moleculeList:
    molec = mol[:-1]
    newMolList.write(molec + " ")
    a = open("../formatted_data/" + molec + "_atoms.txt", "r")
    atomic = open("../formatted_data/features/" + molec + "_atomFeatures.txt", "w")
    previousAtNo = ""
    for line in a:
        atomNo = line.split()[4]
        conformer = line.split()[3]
        atom = line.split()[8]
        if conformer == "1":
            atomic.write(atomNo + " " + atom + "\n")
            previousAtNo = atomNo
        else:
            break
    atomic.close()
    newMolList.write(previousAtNo + "\n")

newMolList.close()
moleculeList.close()